package qz.printer.status.printer;

import qz.printer.status.NativeStatus;

import java.util.Locale;
import java.util.SortedMap;
import java.util.TreeMap;

import static  qz.printer.status.printer.CupsPrinterStatusMap.CupsPrinterStatusType.*;

public enum CupsPrinterStatusMap implements NativeStatus.NativeMap {
    // printer-state
    IDLE(STATE, NativePrinterStatus.OK), // idle
    PROCESSING(STATE, NativePrinterStatus.PROCESSING), // processing
    STOPPED(STATE, NativePrinterStatus.ERROR), // stopped

    // printer-state-reasons.  NativePrinterStatus.UNKNOWN_STATUS will fallback to the printer-state instead
    // Mapped printer-state-reasons
    OTHER(REASON, NativePrinterStatus.UNKNOWN), // "other"
    NONE(REASON, NativePrinterStatus.UNKNOWN), // "none"
    MEDIA_NEEDED(REASON, NativePrinterStatus.PAPER_OUT), // "media-needed"
    MEDIA_JAM(REASON, NativePrinterStatus.PAPER_JAM), // "media-jam"
    MOVING_TO_PAUSED(REASON, NativePrinterStatus.OK), // "moving-to-paused"
    PAUSED(REASON, NativePrinterStatus.PAUSED), // "paused"
    SHUTDOWN(REASON, NativePrinterStatus.OFFLINE), // "shutdown"
    CONNECTING_TO_DEVICE(REASON, NativePrinterStatus.OK), // "connecting-to-device"
    TIMED_OUT(REASON, NativePrinterStatus.NOT_AVAILABLE), // "timed-out"
    STOPPING(REASON, NativePrinterStatus.OK), // "stopping"
    STOPPED_PARTLY(REASON, NativePrinterStatus.PAUSED), // "stopped-partly"
    TONER_LOW(REASON, NativePrinterStatus.TONER_LOW), // "toner-low"
    TONER_EMPTY(REASON, NativePrinterStatus.NO_TONER), // "toner-empty"
    SPOOL_AREA_FULL(REASON, NativePrinterStatus.OUT_OF_MEMORY), // "spool-area-full"
    COVER_OPEN(REASON, NativePrinterStatus.DOOR_OPEN), // "cover-open"
    INTERLOCK_OPEN(REASON, NativePrinterStatus.DOOR_OPEN), // "interlock-open"
    DOOR_OPEN(REASON, NativePrinterStatus.DOOR_OPEN), // "door-open"
    INPUT_TRAY_MISSING(REASON, NativePrinterStatus.PAPER_PROBLEM), // "input-tray-missing"
    MEDIA_LOW(REASON, NativePrinterStatus.PAPER_PROBLEM), // "media-low"
    MEDIA_EMPTY(REASON, NativePrinterStatus.PAPER_OUT), // "media-empty"
    OUTPUT_TRAY_MISSING(REASON, NativePrinterStatus.PAPER_PROBLEM), // "output-tray-missing"
    //not a great match
    OUTPUT_AREA_ALMOST_FULL(REASON, NativePrinterStatus.TONER_LOW), // "output-area-almost-full"
    OUTPUT_AREA_FULL(REASON, NativePrinterStatus.OUTPUT_BIN_FULL), // "output-area-full"
    MARKER_SUPPLY_LOW(REASON, NativePrinterStatus.TONER_LOW), // "marker-supply-low"
    MARKER_SUPPLY_EMPTY(REASON, NativePrinterStatus.NO_TONER), // "marker-supply-empty"
    // not a great match
    MARKER_WASTE_ALMOST_FULL(REASON, NativePrinterStatus.TONER_LOW), // "marker-waste-almost-full"
    MARKER_WASTE_FULL(REASON, NativePrinterStatus.NO_TONER), // "marker-waste-full"
    FUSER_OVER_TEMP(REASON, NativePrinterStatus.WARMING_UP), // "fuser-over-temp"
    FUSER_UNDER_TEMP(REASON, NativePrinterStatus.WARMING_UP), // "fuser-under-temp"
    // not a great match
    OPC_NEAR_EOL(REASON, NativePrinterStatus.TONER_LOW), // "opc-near-eol"
    OPC_LIFE_OVER(REASON, NativePrinterStatus.NO_TONER), // "opc-life-over"
    DEVELOPER_LOW(REASON, NativePrinterStatus.TONER_LOW), // "developer-low"
    DEVELOPER_EMPTY(REASON, NativePrinterStatus.NO_TONER), // "developer-empty"
    INTERPRETER_RESOURCE_UNAVAILABLE(REASON, NativePrinterStatus.SERVER_UNKNOWN), // "interpreter-resource-unavailable"

    // CUPS defined states (defined by CUPS, but not part of the IPP specification)
    OFFLINE(REASON, NativePrinterStatus.OFFLINE), // "offline"
    CUPS_INSECURE_FILTER(REASON, NativePrinterStatus.SERVER_UNKNOWN), // "cups-insecure-filter"
    CUPS_MISSING_FILTER(REASON, NativePrinterStatus.ERROR), // "cups-missing-filter"
    CUPS_WAITING_FOR_JOB_COMPLETED(REASON, NativePrinterStatus.PRINTING), // "cups-waiting-for-job-completed");

    // Unmapped printer-state-reasons
    ALERT_REMOVAL_OF_BINARY_CHANGE_ENTRY(REASON, NativePrinterStatus.UNKNOWN), // alert-removal-of-binary-change-entry
    BANDER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // bander-added
    BANDER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // bander-almost-empty
    BANDER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // bander-almost-full
    BANDER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // bander-at-limit
    BANDER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // bander-closed
    BANDER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // bander-configuration-change
    BANDER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // bander-cover-closed
    BANDER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // bander-cover-open
    BANDER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // bander-empty
    BANDER_FULL(REASON, NativePrinterStatus.UNKNOWN), // bander-full
    BANDER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // bander-interlock-closed
    BANDER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // bander-interlock-open
    BANDER_JAM(REASON, NativePrinterStatus.UNKNOWN), // bander-jam
    BANDER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // bander-life-almost-over
    BANDER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // bander-life-over
    BANDER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // bander-memory-exhausted
    BANDER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // bander-missing
    BANDER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // bander-motor-failure
    BANDER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // bander-near-limit
    BANDER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // bander-offline
    BANDER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // bander-opened
    BANDER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // bander-over-temperature
    BANDER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // bander-power-saver
    BANDER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // bander-recoverable-failure
    BANDER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // bander-recoverable-storage
    BANDER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // bander-removed
    BANDER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // bander-resource-added
    BANDER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // bander-resource-removed
    BANDER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // bander-thermistor-failure
    BANDER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // bander-timing-failure
    BANDER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // bander-turned-off
    BANDER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // bander-turned-on
    BANDER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // bander-under-temperature
    BANDER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // bander-unrecoverable-failure
    BANDER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // bander-unrecoverable-storage-error
    BANDER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // bander-warming-up
    BINDER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // binder-added
    BINDER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // binder-almost-empty
    BINDER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // binder-almost-full
    BINDER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // binder-at-limit
    BINDER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // binder-closed
    BINDER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // binder-configuration-change
    BINDER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // binder-cover-closed
    BINDER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // binder-cover-open
    BINDER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // binder-empty
    BINDER_FULL(REASON, NativePrinterStatus.UNKNOWN), // binder-full
    BINDER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // binder-interlock-closed
    BINDER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // binder-interlock-open
    BINDER_JAM(REASON, NativePrinterStatus.UNKNOWN), // binder-jam
    BINDER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // binder-life-almost-over
    BINDER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // binder-life-over
    BINDER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // binder-memory-exhausted
    BINDER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // binder-missing
    BINDER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // binder-motor-failure
    BINDER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // binder-near-limit
    BINDER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // binder-offline
    BINDER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // binder-opened
    BINDER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // binder-over-temperature
    BINDER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // binder-power-saver
    BINDER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // binder-recoverable-failure
    BINDER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // binder-recoverable-storage
    BINDER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // binder-removed
    BINDER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // binder-resource-added
    BINDER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // binder-resource-removed
    BINDER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // binder-thermistor-failure
    BINDER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // binder-timing-failure
    BINDER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // binder-turned-off
    BINDER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // binder-turned-on
    BINDER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // binder-under-temperature
    BINDER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // binder-unrecoverable-failure
    BINDER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // binder-unrecoverable-storage-error
    BINDER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // binder-warming-up
    CAMERA_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // camera-failure
    CHAMBER_COOLING(REASON, NativePrinterStatus.UNKNOWN), // chamber-cooling
    CHAMBER_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // chamber-failure
    CHAMBER_HEATING(REASON, NativePrinterStatus.UNKNOWN), // chamber-heating
    CHAMBER_TEMPERATURE_HIGH(REASON, NativePrinterStatus.UNKNOWN), // chamber-temperature-high
    CHAMBER_TEMPERATURE_LOW(REASON, NativePrinterStatus.UNKNOWN), // chamber-temperature-low
    CLEANER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // cleaner-life-almost-over
    CLEANER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // cleaner-life-over
    CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // configuration-change
    DEACTIVATED(REASON, NativePrinterStatus.UNKNOWN), // deactivated
    DELETED(REASON, NativePrinterStatus.UNKNOWN), // deleted
    DIE_CUTTER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-added
    DIE_CUTTER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-almost-empty
    DIE_CUTTER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-almost-full
    DIE_CUTTER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-at-limit
    DIE_CUTTER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-closed
    DIE_CUTTER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-configuration-change
    DIE_CUTTER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-cover-closed
    DIE_CUTTER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-cover-open
    DIE_CUTTER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-empty
    DIE_CUTTER_FULL(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-full
    DIE_CUTTER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-interlock-closed
    DIE_CUTTER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-interlock-open
    DIE_CUTTER_JAM(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-jam
    DIE_CUTTER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-life-almost-over
    DIE_CUTTER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-life-over
    DIE_CUTTER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-memory-exhausted
    DIE_CUTTER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-missing
    DIE_CUTTER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-motor-failure
    DIE_CUTTER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-near-limit
    DIE_CUTTER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-offline
    DIE_CUTTER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-opened
    DIE_CUTTER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-over-temperature
    DIE_CUTTER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-power-saver
    DIE_CUTTER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-recoverable-failure
    DIE_CUTTER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-recoverable-storage
    DIE_CUTTER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-removed
    DIE_CUTTER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-resource-added
    DIE_CUTTER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-resource-removed
    DIE_CUTTER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-thermistor-failure
    DIE_CUTTER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-timing-failure
    DIE_CUTTER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-turned-off
    DIE_CUTTER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-turned-on
    DIE_CUTTER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-under-temperature
    DIE_CUTTER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-unrecoverable-failure
    DIE_CUTTER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-unrecoverable-storage-error
    DIE_CUTTER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // die-cutter-warming-up
    EXTRUDER_COOLING(REASON, NativePrinterStatus.UNKNOWN), // extruder-cooling
    EXTRUDER_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // extruder-failure
    EXTRUDER_HEATING(REASON, NativePrinterStatus.UNKNOWN), // extruder-heating
    EXTRUDER_JAM(REASON, NativePrinterStatus.UNKNOWN), // extruder-jam
    EXTRUDER_TEMPERATURE_HIGH(REASON, NativePrinterStatus.UNKNOWN), // extruder-temperature-high
    EXTRUDER_TEMPERATURE_LOW(REASON, NativePrinterStatus.UNKNOWN), // extruder-temperature-low
    FAN_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // fan-failure
    FAX_MODEM_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // fax-modem-life-almost-over
    FAX_MODEM_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // fax-modem-life-over
    FAX_MODEM_MISSING(REASON, NativePrinterStatus.UNKNOWN), // fax-modem-missing
    FAX_MODEM_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // fax-modem-turned-off
    FAX_MODEM_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // fax-modem-turned-on
    FOLDER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // folder-added
    FOLDER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // folder-almost-empty
    FOLDER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // folder-almost-full
    FOLDER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // folder-at-limit
    FOLDER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // folder-closed
    FOLDER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // folder-configuration-change
    FOLDER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // folder-cover-closed
    FOLDER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // folder-cover-open
    FOLDER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // folder-empty
    FOLDER_FULL(REASON, NativePrinterStatus.UNKNOWN), // folder-full
    FOLDER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // folder-interlock-closed
    FOLDER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // folder-interlock-open
    FOLDER_JAM(REASON, NativePrinterStatus.UNKNOWN), // folder-jam
    FOLDER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // folder-life-almost-over
    FOLDER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // folder-life-over
    FOLDER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // folder-memory-exhausted
    FOLDER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // folder-missing
    FOLDER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // folder-motor-failure
    FOLDER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // folder-near-limit
    FOLDER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // folder-offline
    FOLDER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // folder-opened
    FOLDER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // folder-over-temperature
    FOLDER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // folder-power-saver
    FOLDER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // folder-recoverable-failure
    FOLDER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // folder-recoverable-storage
    FOLDER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // folder-removed
    FOLDER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // folder-resource-added
    FOLDER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // folder-resource-removed
    FOLDER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // folder-thermistor-failure
    FOLDER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // folder-timing-failure
    FOLDER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // folder-turned-off
    FOLDER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // folder-turned-on
    FOLDER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // folder-under-temperature
    FOLDER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // folder-unrecoverable-failure
    FOLDER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // folder-unrecoverable-storage-error
    FOLDER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // folder-warming-up
    HIBERNATE(REASON, NativePrinterStatus.UNKNOWN), // hibernate
    HOLD_NEW_JOBS(REASON, NativePrinterStatus.UNKNOWN), // hold-new-jobs
    IDENTIFY_PRINTER_REQUESTED(REASON, NativePrinterStatus.UNKNOWN), // identify-printer-requested
    IMPRINTER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-added
    IMPRINTER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // imprinter-almost-empty
    IMPRINTER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // imprinter-almost-full
    IMPRINTER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // imprinter-at-limit
    IMPRINTER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-closed
    IMPRINTER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-configuration-change
    IMPRINTER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-cover-closed
    IMPRINTER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // imprinter-cover-open
    IMPRINTER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // imprinter-empty
    IMPRINTER_FULL(REASON, NativePrinterStatus.UNKNOWN), // imprinter-full
    IMPRINTER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-interlock-closed
    IMPRINTER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // imprinter-interlock-open
    IMPRINTER_JAM(REASON, NativePrinterStatus.UNKNOWN), // imprinter-jam
    IMPRINTER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // imprinter-life-almost-over
    IMPRINTER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // imprinter-life-over
    IMPRINTER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-memory-exhausted
    IMPRINTER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // imprinter-missing
    IMPRINTER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-motor-failure
    IMPRINTER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // imprinter-near-limit
    IMPRINTER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-offline
    IMPRINTER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-opened
    IMPRINTER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-over-temperature
    IMPRINTER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // imprinter-power-saver
    IMPRINTER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-recoverable-failure
    IMPRINTER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-recoverable-storage
    IMPRINTER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-removed
    IMPRINTER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-resource-added
    IMPRINTER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // imprinter-resource-removed
    IMPRINTER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-thermistor-failure
    IMPRINTER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-timing-failure
    IMPRINTER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // imprinter-turned-off
    IMPRINTER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // imprinter-turned-on
    IMPRINTER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-under-temperature
    IMPRINTER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // imprinter-unrecoverable-failure
    IMPRINTER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // imprinter-unrecoverable-storage-error
    IMPRINTER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // imprinter-warming-up
    INPUT_CANNOT_FEED_SIZE_SELECTED(REASON, NativePrinterStatus.UNKNOWN), // input-cannot-feed-size-selected
    INPUT_MANUAL_INPUT_REQUEST(REASON, NativePrinterStatus.UNKNOWN), // input-manual-input-request
    INPUT_MEDIA_COLOR_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // input-media-color-change
    INPUT_MEDIA_FORM_PARTS_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // input-media-form-parts-change
    INPUT_MEDIA_SIZE_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // input-media-size-change
    INPUT_MEDIA_TRAY_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // input-media-tray-failure
    INPUT_MEDIA_TRAY_FEED_ERROR(REASON, NativePrinterStatus.UNKNOWN), // input-media-tray-feed-error
    INPUT_MEDIA_TRAY_JAM(REASON, NativePrinterStatus.UNKNOWN), // input-media-tray-jam
    INPUT_MEDIA_TYPE_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // input-media-type-change
    INPUT_MEDIA_WEIGHT_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // input-media-weight-change
    INPUT_PICK_ROLLER_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // input-pick-roller-failure
    INPUT_PICK_ROLLER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // input-pick-roller-life-over
    INPUT_PICK_ROLLER_LIFE_WARN(REASON, NativePrinterStatus.UNKNOWN), // input-pick-roller-life-warn
    INPUT_PICK_ROLLER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // input-pick-roller-missing
    INPUT_TRAY_ELEVATION_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // input-tray-elevation-failure
    INPUT_TRAY_POSITION_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // input-tray-position-failure
    INSERTER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // inserter-added
    INSERTER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // inserter-almost-empty
    INSERTER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // inserter-almost-full
    INSERTER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // inserter-at-limit
    INSERTER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // inserter-closed
    INSERTER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // inserter-configuration-change
    INSERTER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // inserter-cover-closed
    INSERTER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // inserter-cover-open
    INSERTER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // inserter-empty
    INSERTER_FULL(REASON, NativePrinterStatus.UNKNOWN), // inserter-full
    INSERTER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // inserter-interlock-closed
    INSERTER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // inserter-interlock-open
    INSERTER_JAM(REASON, NativePrinterStatus.UNKNOWN), // inserter-jam
    INSERTER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // inserter-life-almost-over
    INSERTER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // inserter-life-over
    INSERTER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // inserter-memory-exhausted
    INSERTER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // inserter-missing
    INSERTER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-motor-failure
    INSERTER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // inserter-near-limit
    INSERTER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // inserter-offline
    INSERTER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // inserter-opened
    INSERTER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-over-temperature
    INSERTER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // inserter-power-saver
    INSERTER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-recoverable-failure
    INSERTER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // inserter-recoverable-storage
    INSERTER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // inserter-removed
    INSERTER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // inserter-resource-added
    INSERTER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // inserter-resource-removed
    INSERTER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-thermistor-failure
    INSERTER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-timing-failure
    INSERTER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // inserter-turned-off
    INSERTER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // inserter-turned-on
    INSERTER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-under-temperature
    INSERTER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // inserter-unrecoverable-failure
    INSERTER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // inserter-unrecoverable-storage-error
    INSERTER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // inserter-warming-up
    INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // interlock-closed
    INTERPRETER_CARTRIDGE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // interpreter-cartridge-added
    INTERPRETER_CARTRIDGE_DELETED(REASON, NativePrinterStatus.UNKNOWN), // interpreter-cartridge-deleted
    INTERPRETER_COMPLEX_PAGE_ENCOUNTERED(REASON, NativePrinterStatus.UNKNOWN), // interpreter-complex-page-encountered
    INTERPRETER_MEMORY_DECREASE(REASON, NativePrinterStatus.UNKNOWN), // interpreter-memory-decrease
    INTERPRETER_MEMORY_INCREASE(REASON, NativePrinterStatus.UNKNOWN), // interpreter-memory-increase
    INTERPRETER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // interpreter-resource-added
    INTERPRETER_RESOURCE_DELETED(REASON, NativePrinterStatus.UNKNOWN), // interpreter-resource-deleted
    LAMP_AT_EOL(REASON, NativePrinterStatus.UNKNOWN), // lamp-at-eol
    LAMP_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // lamp-failure
    LAMP_NEAR_EOL(REASON, NativePrinterStatus.UNKNOWN), // lamp-near-eol
    LASER_AT_EOL(REASON, NativePrinterStatus.UNKNOWN), // laser-at-eol
    LASER_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // laser-failure
    LASER_NEAR_EOL(REASON, NativePrinterStatus.UNKNOWN), // laser-near-eol
    MAKE_ENVELOPE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-added
    MAKE_ENVELOPE_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-almost-empty
    MAKE_ENVELOPE_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-almost-full
    MAKE_ENVELOPE_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-at-limit
    MAKE_ENVELOPE_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-closed
    MAKE_ENVELOPE_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-configuration-change
    MAKE_ENVELOPE_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-cover-closed
    MAKE_ENVELOPE_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-cover-open
    MAKE_ENVELOPE_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-empty
    MAKE_ENVELOPE_FULL(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-full
    MAKE_ENVELOPE_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-interlock-closed
    MAKE_ENVELOPE_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-interlock-open
    MAKE_ENVELOPE_JAM(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-jam
    MAKE_ENVELOPE_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-life-almost-over
    MAKE_ENVELOPE_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-life-over
    MAKE_ENVELOPE_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-memory-exhausted
    MAKE_ENVELOPE_MISSING(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-missing
    MAKE_ENVELOPE_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-motor-failure
    MAKE_ENVELOPE_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-near-limit
    MAKE_ENVELOPE_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-offline
    MAKE_ENVELOPE_OPENED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-opened
    MAKE_ENVELOPE_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-over-temperature
    MAKE_ENVELOPE_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-power-saver
    MAKE_ENVELOPE_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-recoverable-failure
    MAKE_ENVELOPE_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-recoverable-storage
    MAKE_ENVELOPE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-removed
    MAKE_ENVELOPE_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-resource-added
    MAKE_ENVELOPE_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-resource-removed
    MAKE_ENVELOPE_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-thermistor-failure
    MAKE_ENVELOPE_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-timing-failure
    MAKE_ENVELOPE_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-turned-off
    MAKE_ENVELOPE_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-turned-on
    MAKE_ENVELOPE_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-under-temperature
    MAKE_ENVELOPE_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-unrecoverable-failure
    MAKE_ENVELOPE_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-unrecoverable-storage-error
    MAKE_ENVELOPE_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // make-envelope-warming-up
    MARKER_ADJUSTING_PRINT_QUALITY(REASON, NativePrinterStatus.UNKNOWN), // marker-adjusting-print-quality
    MARKER_CLEANER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-cleaner-missing
    MARKER_DEVELOPER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-developer-almost-empty
    MARKER_DEVELOPER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-developer-empty
    MARKER_DEVELOPER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-developer-missing
    MARKER_FUSER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-fuser-missing
    MARKER_FUSER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // marker-fuser-thermistor-failure
    MARKER_FUSER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // marker-fuser-timing-failure
    MARKER_INK_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-ink-almost-empty
    MARKER_INK_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-ink-empty
    MARKER_INK_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-ink-missing
    MARKER_OPC_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-opc-missing
    MARKER_PRINT_RIBBON_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-print-ribbon-almost-empty
    MARKER_PRINT_RIBBON_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-print-ribbon-empty
    MARKER_PRINT_RIBBON_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-print-ribbon-missing
    MARKER_SUPPLY_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // marker-supply-almost-empty
    MARKER_SUPPLY_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-supply-missing
    MARKER_TONER_CARTRIDGE_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-toner-cartridge-missing
    MARKER_TONER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-toner-missing
    MARKER_WASTE_INK_RECEPTACLE_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-ink-receptacle-almost-full
    MARKER_WASTE_INK_RECEPTACLE_FULL(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-ink-receptacle-full
    MARKER_WASTE_INK_RECEPTACLE_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-ink-receptacle-missing
    MARKER_WASTE_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-missing
    MARKER_WASTE_TONER_RECEPTACLE_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-toner-receptacle-almost-full
    MARKER_WASTE_TONER_RECEPTACLE_FULL(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-toner-receptacle-full
    MARKER_WASTE_TONER_RECEPTACLE_MISSING(REASON, NativePrinterStatus.UNKNOWN), // marker-waste-toner-receptacle-missing
    MATERIAL_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // material-empty
    MATERIAL_LOW(REASON, NativePrinterStatus.UNKNOWN), // material-low
    MATERIAL_NEEDED(REASON, NativePrinterStatus.UNKNOWN), // material-needed
    MEDIA_DRYING(REASON, NativePrinterStatus.UNKNOWN), // media-drying
    MEDIA_PATH_CANNOT_DUPLEX_MEDIA_SELECTED(REASON, NativePrinterStatus.UNKNOWN), // media-path-cannot-duplex-media-selected
    MEDIA_PATH_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // media-path-failure
    MEDIA_PATH_INPUT_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // media-path-input-empty
    MEDIA_PATH_INPUT_FEED_ERROR(REASON, NativePrinterStatus.UNKNOWN), // media-path-input-feed-error
    MEDIA_PATH_INPUT_JAM(REASON, NativePrinterStatus.UNKNOWN), // media-path-input-jam
    MEDIA_PATH_INPUT_REQUEST(REASON, NativePrinterStatus.UNKNOWN), // media-path-input-request
    MEDIA_PATH_JAM(REASON, NativePrinterStatus.UNKNOWN), // media-path-jam
    MEDIA_PATH_MEDIA_TRAY_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // media-path-media-tray-almost-full
    MEDIA_PATH_MEDIA_TRAY_FULL(REASON, NativePrinterStatus.UNKNOWN), // media-path-media-tray-full
    MEDIA_PATH_MEDIA_TRAY_MISSING(REASON, NativePrinterStatus.UNKNOWN), // media-path-media-tray-missing
    MEDIA_PATH_OUTPUT_FEED_ERROR(REASON, NativePrinterStatus.UNKNOWN), // media-path-output-feed-error
    MEDIA_PATH_OUTPUT_FULL(REASON, NativePrinterStatus.UNKNOWN), // media-path-output-full
    MEDIA_PATH_OUTPUT_JAM(REASON, NativePrinterStatus.UNKNOWN), // media-path-output-jam
    MEDIA_PATH_PICK_ROLLER_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // media-path-pick-roller-failure
    MEDIA_PATH_PICK_ROLLER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // media-path-pick-roller-life-over
    MEDIA_PATH_PICK_ROLLER_LIFE_WARN(REASON, NativePrinterStatus.UNKNOWN), // media-path-pick-roller-life-warn
    MEDIA_PATH_PICK_ROLLER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // media-path-pick-roller-missing
    MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // motor-failure
    OUTPUT_MAILBOX_SELECT_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // output-mailbox-select-failure
    OUTPUT_MEDIA_TRAY_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // output-media-tray-failure
    OUTPUT_MEDIA_TRAY_FEED_ERROR(REASON, NativePrinterStatus.UNKNOWN), // output-media-tray-feed-error
    OUTPUT_MEDIA_TRAY_JAM(REASON, NativePrinterStatus.UNKNOWN), // output-media-tray-jam
    PERFORATER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // perforater-added
    PERFORATER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // perforater-almost-empty
    PERFORATER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // perforater-almost-full
    PERFORATER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // perforater-at-limit
    PERFORATER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // perforater-closed
    PERFORATER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // perforater-configuration-change
    PERFORATER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // perforater-cover-closed
    PERFORATER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // perforater-cover-open
    PERFORATER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // perforater-empty
    PERFORATER_FULL(REASON, NativePrinterStatus.UNKNOWN), // perforater-full
    PERFORATER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // perforater-interlock-closed
    PERFORATER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // perforater-interlock-open
    PERFORATER_JAM(REASON, NativePrinterStatus.UNKNOWN), // perforater-jam
    PERFORATER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // perforater-life-almost-over
    PERFORATER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // perforater-life-over
    PERFORATER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // perforater-memory-exhausted
    PERFORATER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // perforater-missing
    PERFORATER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-motor-failure
    PERFORATER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // perforater-near-limit
    PERFORATER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // perforater-offline
    PERFORATER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // perforater-opened
    PERFORATER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-over-temperature
    PERFORATER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // perforater-power-saver
    PERFORATER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-recoverable-failure
    PERFORATER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // perforater-recoverable-storage
    PERFORATER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // perforater-removed
    PERFORATER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // perforater-resource-added
    PERFORATER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // perforater-resource-removed
    PERFORATER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-thermistor-failure
    PERFORATER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-timing-failure
    PERFORATER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // perforater-turned-off
    PERFORATER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // perforater-turned-on
    PERFORATER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-under-temperature
    PERFORATER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // perforater-unrecoverable-failure
    PERFORATER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // perforater-unrecoverable-storage-error
    PERFORATER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // perforater-warming-up
    PLATFORM_COOLING(REASON, NativePrinterStatus.UNKNOWN), // platform-cooling
    PLATFORM_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // platform-failure
    PLATFORM_HEATING(REASON, NativePrinterStatus.UNKNOWN), // platform-heating
    PLATFORM_TEMPERATURE_HIGH(REASON, NativePrinterStatus.UNKNOWN), // platform-temperature-high
    PLATFORM_TEMPERATURE_LOW(REASON, NativePrinterStatus.UNKNOWN), // platform-temperature-low
    POWER_DOWN(REASON, NativePrinterStatus.UNKNOWN), // power-down
    POWER_UP(REASON, NativePrinterStatus.UNKNOWN), // power-up
    PRINTER_MANUAL_RESET(REASON, NativePrinterStatus.UNKNOWN), // printer-manual-reset
    PRINTER_NMS_RESET(REASON, NativePrinterStatus.UNKNOWN), // printer-nms-reset
    PRINTER_READY_TO_PRINT(REASON, NativePrinterStatus.UNKNOWN), // printer-ready-to-print
    PUNCHER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // puncher-added
    PUNCHER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // puncher-almost-empty
    PUNCHER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // puncher-almost-full
    PUNCHER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // puncher-at-limit
    PUNCHER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // puncher-closed
    PUNCHER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // puncher-configuration-change
    PUNCHER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // puncher-cover-closed
    PUNCHER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // puncher-cover-open
    PUNCHER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // puncher-empty
    PUNCHER_FULL(REASON, NativePrinterStatus.UNKNOWN), // puncher-full
    PUNCHER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // puncher-interlock-closed
    PUNCHER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // puncher-interlock-open
    PUNCHER_JAM(REASON, NativePrinterStatus.UNKNOWN), // puncher-jam
    PUNCHER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // puncher-life-almost-over
    PUNCHER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // puncher-life-over
    PUNCHER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // puncher-memory-exhausted
    PUNCHER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // puncher-missing
    PUNCHER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-motor-failure
    PUNCHER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // puncher-near-limit
    PUNCHER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // puncher-offline
    PUNCHER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // puncher-opened
    PUNCHER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-over-temperature
    PUNCHER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // puncher-power-saver
    PUNCHER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-recoverable-failure
    PUNCHER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // puncher-recoverable-storage
    PUNCHER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // puncher-removed
    PUNCHER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // puncher-resource-added
    PUNCHER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // puncher-resource-removed
    PUNCHER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-thermistor-failure
    PUNCHER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-timing-failure
    PUNCHER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // puncher-turned-off
    PUNCHER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // puncher-turned-on
    PUNCHER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-under-temperature
    PUNCHER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // puncher-unrecoverable-failure
    PUNCHER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // puncher-unrecoverable-storage-error
    PUNCHER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // puncher-warming-up
    RESUMING(REASON, NativePrinterStatus.UNKNOWN), // resuming
    SCAN_MEDIA_PATH_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-failure
    SCAN_MEDIA_PATH_INPUT_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-input-empty
    SCAN_MEDIA_PATH_INPUT_FEED_ERROR(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-input-feed-error
    SCAN_MEDIA_PATH_INPUT_JAM(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-input-jam
    SCAN_MEDIA_PATH_INPUT_REQUEST(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-input-request
    SCAN_MEDIA_PATH_JAM(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-jam
    SCAN_MEDIA_PATH_OUTPUT_FEED_ERROR(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-output-feed-error
    SCAN_MEDIA_PATH_OUTPUT_FULL(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-output-full
    SCAN_MEDIA_PATH_OUTPUT_JAM(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-output-jam
    SCAN_MEDIA_PATH_PICK_ROLLER_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-pick-roller-failure
    SCAN_MEDIA_PATH_PICK_ROLLER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-pick-roller-life-over
    SCAN_MEDIA_PATH_PICK_ROLLER_LIFE_WARN(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-pick-roller-life-warn
    SCAN_MEDIA_PATH_PICK_ROLLER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-pick-roller-missing
    SCAN_MEDIA_PATH_TRAY_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-tray-almost-full
    SCAN_MEDIA_PATH_TRAY_FULL(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-tray-full
    SCAN_MEDIA_PATH_TRAY_MISSING(REASON, NativePrinterStatus.UNKNOWN), // scan-media-path-tray-missing
    SCANNER_LIGHT_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // scanner-light-failure
    SCANNER_LIGHT_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // scanner-light-life-almost-over
    SCANNER_LIGHT_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // scanner-light-life-over
    SCANNER_LIGHT_MISSING(REASON, NativePrinterStatus.UNKNOWN), // scanner-light-missing
    SCANNER_SENSOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // scanner-sensor-failure
    SCANNER_SENSOR_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // scanner-sensor-life-almost-over
    SCANNER_SENSOR_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // scanner-sensor-life-over
    SCANNER_SENSOR_MISSING(REASON, NativePrinterStatus.UNKNOWN), // scanner-sensor-missing
    SEPARATION_CUTTER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-added
    SEPARATION_CUTTER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-almost-empty
    SEPARATION_CUTTER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-almost-full
    SEPARATION_CUTTER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-at-limit
    SEPARATION_CUTTER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-closed
    SEPARATION_CUTTER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-configuration-change
    SEPARATION_CUTTER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-cover-closed
    SEPARATION_CUTTER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-cover-open
    SEPARATION_CUTTER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-empty
    SEPARATION_CUTTER_FULL(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-full
    SEPARATION_CUTTER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-interlock-closed
    SEPARATION_CUTTER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-interlock-open
    SEPARATION_CUTTER_JAM(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-jam
    SEPARATION_CUTTER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-life-almost-over
    SEPARATION_CUTTER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-life-over
    SEPARATION_CUTTER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-memory-exhausted
    SEPARATION_CUTTER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-missing
    SEPARATION_CUTTER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-motor-failure
    SEPARATION_CUTTER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-near-limit
    SEPARATION_CUTTER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-offline
    SEPARATION_CUTTER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-opened
    SEPARATION_CUTTER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-over-temperature
    SEPARATION_CUTTER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-power-saver
    SEPARATION_CUTTER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-recoverable-failure
    SEPARATION_CUTTER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-recoverable-storage
    SEPARATION_CUTTER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-removed
    SEPARATION_CUTTER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-resource-added
    SEPARATION_CUTTER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-resource-removed
    SEPARATION_CUTTER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-thermistor-failure
    SEPARATION_CUTTER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-timing-failure
    SEPARATION_CUTTER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-turned-off
    SEPARATION_CUTTER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-turned-on
    SEPARATION_CUTTER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-under-temperature
    SEPARATION_CUTTER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-unrecoverable-failure
    SEPARATION_CUTTER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-unrecoverable-storage-error
    SEPARATION_CUTTER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // separation-cutter-warming-up
    SHEET_ROTATOR_ADDED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-added
    SHEET_ROTATOR_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-almost-empty
    SHEET_ROTATOR_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-almost-full
    SHEET_ROTATOR_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-at-limit
    SHEET_ROTATOR_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-closed
    SHEET_ROTATOR_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-configuration-change
    SHEET_ROTATOR_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-cover-closed
    SHEET_ROTATOR_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-cover-open
    SHEET_ROTATOR_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-empty
    SHEET_ROTATOR_FULL(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-full
    SHEET_ROTATOR_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-interlock-closed
    SHEET_ROTATOR_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-interlock-open
    SHEET_ROTATOR_JAM(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-jam
    SHEET_ROTATOR_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-life-almost-over
    SHEET_ROTATOR_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-life-over
    SHEET_ROTATOR_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-memory-exhausted
    SHEET_ROTATOR_MISSING(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-missing
    SHEET_ROTATOR_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-motor-failure
    SHEET_ROTATOR_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-near-limit
    SHEET_ROTATOR_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-offline
    SHEET_ROTATOR_OPENED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-opened
    SHEET_ROTATOR_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-over-temperature
    SHEET_ROTATOR_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-power-saver
    SHEET_ROTATOR_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-recoverable-failure
    SHEET_ROTATOR_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-recoverable-storage
    SHEET_ROTATOR_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-removed
    SHEET_ROTATOR_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-resource-added
    SHEET_ROTATOR_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-resource-removed
    SHEET_ROTATOR_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-thermistor-failure
    SHEET_ROTATOR_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-timing-failure
    SHEET_ROTATOR_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-turned-off
    SHEET_ROTATOR_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-turned-on
    SHEET_ROTATOR_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-under-temperature
    SHEET_ROTATOR_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-unrecoverable-failure
    SHEET_ROTATOR_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-unrecoverable-storage-error
    SHEET_ROTATOR_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // sheet-rotator-warming-up
    SLITTER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // slitter-added
    SLITTER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // slitter-almost-empty
    SLITTER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // slitter-almost-full
    SLITTER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // slitter-at-limit
    SLITTER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // slitter-closed
    SLITTER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // slitter-configuration-change
    SLITTER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // slitter-cover-closed
    SLITTER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // slitter-cover-open
    SLITTER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // slitter-empty
    SLITTER_FULL(REASON, NativePrinterStatus.UNKNOWN), // slitter-full
    SLITTER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // slitter-interlock-closed
    SLITTER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // slitter-interlock-open
    SLITTER_JAM(REASON, NativePrinterStatus.UNKNOWN), // slitter-jam
    SLITTER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // slitter-life-almost-over
    SLITTER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // slitter-life-over
    SLITTER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // slitter-memory-exhausted
    SLITTER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // slitter-missing
    SLITTER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-motor-failure
    SLITTER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // slitter-near-limit
    SLITTER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // slitter-offline
    SLITTER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // slitter-opened
    SLITTER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-over-temperature
    SLITTER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // slitter-power-saver
    SLITTER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-recoverable-failure
    SLITTER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // slitter-recoverable-storage
    SLITTER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // slitter-removed
    SLITTER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // slitter-resource-added
    SLITTER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // slitter-resource-removed
    SLITTER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-thermistor-failure
    SLITTER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-timing-failure
    SLITTER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // slitter-turned-off
    SLITTER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // slitter-turned-on
    SLITTER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-under-temperature
    SLITTER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // slitter-unrecoverable-failure
    SLITTER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // slitter-unrecoverable-storage-error
    SLITTER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // slitter-warming-up
    STACKER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // stacker-added
    STACKER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // stacker-almost-empty
    STACKER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // stacker-almost-full
    STACKER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // stacker-at-limit
    STACKER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stacker-closed
    STACKER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // stacker-configuration-change
    STACKER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stacker-cover-closed
    STACKER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // stacker-cover-open
    STACKER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // stacker-empty
    STACKER_FULL(REASON, NativePrinterStatus.UNKNOWN), // stacker-full
    STACKER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stacker-interlock-closed
    STACKER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // stacker-interlock-open
    STACKER_JAM(REASON, NativePrinterStatus.UNKNOWN), // stacker-jam
    STACKER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // stacker-life-almost-over
    STACKER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // stacker-life-over
    STACKER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // stacker-memory-exhausted
    STACKER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // stacker-missing
    STACKER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-motor-failure
    STACKER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // stacker-near-limit
    STACKER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // stacker-offline
    STACKER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // stacker-opened
    STACKER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-over-temperature
    STACKER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // stacker-power-saver
    STACKER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-recoverable-failure
    STACKER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // stacker-recoverable-storage
    STACKER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // stacker-removed
    STACKER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // stacker-resource-added
    STACKER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // stacker-resource-removed
    STACKER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-thermistor-failure
    STACKER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-timing-failure
    STACKER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // stacker-turned-off
    STACKER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // stacker-turned-on
    STACKER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-under-temperature
    STACKER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stacker-unrecoverable-failure
    STACKER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // stacker-unrecoverable-storage-error
    STACKER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // stacker-warming-up
    STANDBY(REASON, NativePrinterStatus.UNKNOWN), // standby
    STAPLER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // stapler-added
    STAPLER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // stapler-almost-empty
    STAPLER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // stapler-almost-full
    STAPLER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // stapler-at-limit
    STAPLER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stapler-closed
    STAPLER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // stapler-configuration-change
    STAPLER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stapler-cover-closed
    STAPLER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // stapler-cover-open
    STAPLER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // stapler-empty
    STAPLER_FULL(REASON, NativePrinterStatus.UNKNOWN), // stapler-full
    STAPLER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stapler-interlock-closed
    STAPLER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // stapler-interlock-open
    STAPLER_JAM(REASON, NativePrinterStatus.UNKNOWN), // stapler-jam
    STAPLER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // stapler-life-almost-over
    STAPLER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // stapler-life-over
    STAPLER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // stapler-memory-exhausted
    STAPLER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // stapler-missing
    STAPLER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-motor-failure
    STAPLER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // stapler-near-limit
    STAPLER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // stapler-offline
    STAPLER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // stapler-opened
    STAPLER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-over-temperature
    STAPLER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // stapler-power-saver
    STAPLER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-recoverable-failure
    STAPLER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // stapler-recoverable-storage
    STAPLER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // stapler-removed
    STAPLER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // stapler-resource-added
    STAPLER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // stapler-resource-removed
    STAPLER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-thermistor-failure
    STAPLER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-timing-failure
    STAPLER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // stapler-turned-off
    STAPLER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // stapler-turned-on
    STAPLER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-under-temperature
    STAPLER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stapler-unrecoverable-failure
    STAPLER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // stapler-unrecoverable-storage-error
    STAPLER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // stapler-warming-up
    STITCHER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-added
    STITCHER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // stitcher-almost-empty
    STITCHER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // stitcher-almost-full
    STITCHER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // stitcher-at-limit
    STITCHER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-closed
    STITCHER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-configuration-change
    STITCHER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-cover-closed
    STITCHER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // stitcher-cover-open
    STITCHER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // stitcher-empty
    STITCHER_FULL(REASON, NativePrinterStatus.UNKNOWN), // stitcher-full
    STITCHER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-interlock-closed
    STITCHER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // stitcher-interlock-open
    STITCHER_JAM(REASON, NativePrinterStatus.UNKNOWN), // stitcher-jam
    STITCHER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // stitcher-life-almost-over
    STITCHER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // stitcher-life-over
    STITCHER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-memory-exhausted
    STITCHER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // stitcher-missing
    STITCHER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-motor-failure
    STITCHER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // stitcher-near-limit
    STITCHER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-offline
    STITCHER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-opened
    STITCHER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-over-temperature
    STITCHER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // stitcher-power-saver
    STITCHER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-recoverable-failure
    STITCHER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-recoverable-storage
    STITCHER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-removed
    STITCHER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-resource-added
    STITCHER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // stitcher-resource-removed
    STITCHER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-thermistor-failure
    STITCHER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-timing-failure
    STITCHER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // stitcher-turned-off
    STITCHER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // stitcher-turned-on
    STITCHER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-under-temperature
    STITCHER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // stitcher-unrecoverable-failure
    STITCHER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // stitcher-unrecoverable-storage-error
    STITCHER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // stitcher-warming-up
    SUBUNIT_ADDED(REASON, NativePrinterStatus.UNKNOWN), // subunit-added
    SUBUNIT_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // subunit-almost-empty
    SUBUNIT_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // subunit-almost-full
    SUBUNIT_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // subunit-at-limit
    SUBUNIT_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // subunit-closed
    SUBUNIT_COOLING_DOWN(REASON, NativePrinterStatus.UNKNOWN), // subunit-cooling-down
    SUBUNIT_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // subunit-empty
    SUBUNIT_FULL(REASON, NativePrinterStatus.UNKNOWN), // subunit-full
    SUBUNIT_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // subunit-life-almost-over
    SUBUNIT_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // subunit-life-over
    SUBUNIT_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // subunit-memory-exhausted
    SUBUNIT_MISSING(REASON, NativePrinterStatus.UNKNOWN), // subunit-missing
    SUBUNIT_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-motor-failure
    SUBUNIT_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // subunit-near-limit
    SUBUNIT_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // subunit-offline
    SUBUNIT_OPENED(REASON, NativePrinterStatus.UNKNOWN), // subunit-opened
    SUBUNIT_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-over-temperature
    SUBUNIT_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // subunit-power-saver
    SUBUNIT_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-recoverable-failure
    SUBUNIT_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // subunit-recoverable-storage
    SUBUNIT_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // subunit-removed
    SUBUNIT_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // subunit-resource-added
    SUBUNIT_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // subunit-resource-removed
    SUBUNIT_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-thermistor-failure
    SUBUNIT_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-timing-Failure
    SUBUNIT_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // subunit-turned-off
    SUBUNIT_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // subunit-turned-on
    SUBUNIT_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-under-temperature
    SUBUNIT_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // subunit-unrecoverable-failure
    SUBUNIT_UNRECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // subunit-unrecoverable-storage
    SUBUNIT_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // subunit-warming-up
    SUSPEND(REASON, NativePrinterStatus.UNKNOWN), // suspend
    TESTING(REASON, NativePrinterStatus.UNKNOWN), // testing
    TRIMMER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-added
    TRIMMER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // trimmer-almost-empty
    TRIMMER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // trimmer-almost-full
    TRIMMER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // trimmer-at-limit
    TRIMMER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-closed
    TRIMMER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-configuration-change
    TRIMMER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-cover-closed
    TRIMMER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // trimmer-cover-open
    TRIMMER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // trimmer-empty
    TRIMMER_FULL(REASON, NativePrinterStatus.UNKNOWN), // trimmer-full
    TRIMMER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-interlock-closed
    TRIMMER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // trimmer-interlock-open
    TRIMMER_JAM(REASON, NativePrinterStatus.UNKNOWN), // trimmer-jam
    TRIMMER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // trimmer-life-almost-over
    TRIMMER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // trimmer-life-over
    TRIMMER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-memory-exhausted
    TRIMMER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // trimmer-missing
    TRIMMER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-motor-failure
    TRIMMER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // trimmer-near-limit
    TRIMMER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-offline
    TRIMMER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-opened
    TRIMMER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-over-temperature
    TRIMMER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // trimmer-power-saver
    TRIMMER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-recoverable-failure
    TRIMMER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-recoverable-storage
    TRIMMER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-removed
    TRIMMER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-resource-added
    TRIMMER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // trimmer-resource-removed
    TRIMMER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-thermistor-failure
    TRIMMER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-timing-failure
    TRIMMER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // trimmer-turned-off
    TRIMMER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // trimmer-turned-on
    TRIMMER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-under-temperature
    TRIMMER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // trimmer-unrecoverable-failure
    TRIMMER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // trimmer-unrecoverable-storage-error
    TRIMMER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN), // trimmer-warming-up
    UNKNOWN(REASON, NativePrinterStatus.UNKNOWN), // unknown
    WRAPPER_ADDED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-added
    WRAPPER_ALMOST_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // wrapper-almost-empty
    WRAPPER_ALMOST_FULL(REASON, NativePrinterStatus.UNKNOWN), // wrapper-almost-full
    WRAPPER_AT_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // wrapper-at-limit
    WRAPPER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-closed
    WRAPPER_CONFIGURATION_CHANGE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-configuration-change
    WRAPPER_COVER_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-cover-closed
    WRAPPER_COVER_OPEN(REASON, NativePrinterStatus.UNKNOWN), // wrapper-cover-open
    WRAPPER_EMPTY(REASON, NativePrinterStatus.UNKNOWN), // wrapper-empty
    WRAPPER_FULL(REASON, NativePrinterStatus.UNKNOWN), // wrapper-full
    WRAPPER_INTERLOCK_CLOSED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-interlock-closed
    WRAPPER_INTERLOCK_OPEN(REASON, NativePrinterStatus.UNKNOWN), // wrapper-interlock-open
    WRAPPER_JAM(REASON, NativePrinterStatus.UNKNOWN), // wrapper-jam
    WRAPPER_LIFE_ALMOST_OVER(REASON, NativePrinterStatus.UNKNOWN), // wrapper-life-almost-over
    WRAPPER_LIFE_OVER(REASON, NativePrinterStatus.UNKNOWN), // wrapper-life-over
    WRAPPER_MEMORY_EXHAUSTED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-memory-exhausted
    WRAPPER_MISSING(REASON, NativePrinterStatus.UNKNOWN), // wrapper-missing
    WRAPPER_MOTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-motor-failure
    WRAPPER_NEAR_LIMIT(REASON, NativePrinterStatus.UNKNOWN), // wrapper-near-limit
    WRAPPER_OFFLINE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-offline
    WRAPPER_OPENED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-opened
    WRAPPER_OVER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-over-temperature
    WRAPPER_POWER_SAVER(REASON, NativePrinterStatus.UNKNOWN), // wrapper-power-saver
    WRAPPER_RECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-recoverable-failure
    WRAPPER_RECOVERABLE_STORAGE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-recoverable-storage
    WRAPPER_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-removed
    WRAPPER_RESOURCE_ADDED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-resource-added
    WRAPPER_RESOURCE_REMOVED(REASON, NativePrinterStatus.UNKNOWN), // wrapper-resource-removed
    WRAPPER_THERMISTOR_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-thermistor-failure
    WRAPPER_TIMING_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-timing-failure
    WRAPPER_TURNED_OFF(REASON, NativePrinterStatus.UNKNOWN), // wrapper-turned-off
    WRAPPER_TURNED_ON(REASON, NativePrinterStatus.UNKNOWN), // wrapper-turned-on
    WRAPPER_UNDER_TEMPERATURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-under-temperature
    WRAPPER_UNRECOVERABLE_FAILURE(REASON, NativePrinterStatus.UNKNOWN), // wrapper-unrecoverable-failure
    WRAPPER_UNRECOVERABLE_STORAGE_ERROR(REASON, NativePrinterStatus.UNKNOWN), // wrapper-unrecoverable-storage-error
    WRAPPER_WARMING_UP(REASON, NativePrinterStatus.UNKNOWN); // wrapper-warming-up

    public static SortedMap<String,NativePrinterStatus> sortedReasonLookupTable;
    public static SortedMap<String,NativePrinterStatus> sortedStateLookupTable;

    private NativePrinterStatus parent;
    private CupsPrinterStatusType type;

    enum CupsPrinterStatusType {
        STATE,
        REASON;
    }

    CupsPrinterStatusMap(CupsPrinterStatusType type, NativePrinterStatus parent) {
        this.type = type;
        this.parent = parent;
    }

    public static NativePrinterStatus matchReason(String code) {
        // Initialize a sorted map to speed up lookups
        if(sortedReasonLookupTable == null) {
            sortedReasonLookupTable = new TreeMap<>();
            for(CupsPrinterStatusMap value : values()) {
                if(value.type == REASON) {
                    sortedReasonLookupTable.put(value.name().toLowerCase(Locale.ENGLISH).replace("_", "-"), value.parent);
                }
            }
        }
        return sortedReasonLookupTable.get(code);
    }

    public static NativePrinterStatus matchState(String state) {
        // Initialize a sorted map to speed up lookups
        if(sortedStateLookupTable == null) {
            sortedStateLookupTable = new TreeMap<>();
            for(CupsPrinterStatusMap value : values()) {
                if(value.type == STATE) {
                    sortedStateLookupTable.put(value.name().toLowerCase(Locale.ENGLISH).replace("_", "-"), value.parent);
                }
            }
        }
        return sortedStateLookupTable.getOrDefault(state, NativePrinterStatus.UNKNOWN);
    }

    @Override
    public NativePrinterStatus getParent() {
        return parent;
    }

    @Override
    public Object getRawCode() {
        return name().toLowerCase(Locale.ENGLISH).replace("_", "-");
    }
}
