# For renovate to be able to update version information
# it needs the org and name to look up the latest rev

#------------------------------#
# Main app dependency versions #
#------------------------------#
bc.org=org.bouncycastle
bc.name=bcprov-jdk18on
bc.rev=1.83

flatlaf.org=com.formdev
flatlaf.name=flatlaf
flatlaf.rev=3.7.1

hid4java.org=org.hid4java
hid4java.name=hid4java
hid4java.rev=0.8.0

icu4j.org=com.ibm.icu
icu4j.name=icu4j
icu4j.rev=78.3

jai.org=com.github.jai-imageio
jai.name=jai-imageio-core
jai.rev=1.4.0

javafx.org=org.openjfx
javafx.name=javafx-base
javafx.rev=27-ea+10

semver.org=com.github.zafarkhaja
semver.name=java-semver
semver.rev=0.10.2

jettison.org=org.codehaus.jettison
jettison.name=jettison
jettison.rev=1.5.5

jbig2.org=org.apache.pdfbox
jbig2.name=jbig2-imageio
jbig2.rev=3.0.4

jetty.org=org.eclipse.jetty
jetty.name=jetty-server
jetty.rev=10.0.26

jna.org=net.java.dev.jna
jna.name=jna-platform
jna.rev=5.18.1

jssc.org=io.github.java-native
jssc.name=jssc
jssc.rev=2.10.2

libusb4java.org=org.usb4java
libusb4java.name=libusb4java
libusb4java.rev=1.2.0

log4j.org=org.apache.logging.log4j
log4j.name=log4j-core
log4j.rev=2.25.4

mslinks.org=org.jabref
mslinks.name=mslinks
mslinks.rev=1.1.1

pdfbox.org=org.apache.pdfbox
pdfbox.name=pdfbox
pdfbox.rev=2.0.36

purejavahidapi.org=nyholku
purejavahidapi.name=purejavahidapi
purejavahidapi.rev=0.0.10

servlet-api.org=org.eclipse.jetty.toolchain
servlet-api.name=jetty-servlet-api
servlet-api.rev=4.0.9

twelvemonkeys.org=com.twelvemonkeys.imageio
twelvemonkeys.name=imageio-core
twelvemonkeys.rev=3.13.1

usb-api.org=javax.usb
usb-api.name=usb-api
usb-api.rev=1.0.2

usb4java.org=org.usb4java
usb4java.name=usb4java
usb4java.rev=1.3.0

# TODO: Switch to jakarta org=jakarta.websocket, name=jakarta.websocket, rev=2.3.0-M2
websocket-api.org=javax.websocket
websocket-api.name=javax.websocket-api
websocket-api.rev=1.1

commons-codec.org=commons-codec
commons-codec.name=commons-codec
commons-codec.rev=1.21.0

commons-io.org=commons-io
commons-io.name=commons-io
commons-io.rev=2.21.0

commons-pool2.org=org.apache.commons
commons-pool2.name=commons-pool2
commons-pool2.rev=2.13.1

commons-ssl.org=com.narupley
commons-ssl.name=not-going-to-be-commons-ssl
commons-ssl.rev=0.3.20

#------------------------------#
# Ant-only dependency versions #
#------------------------------#
jsign.org=net.jsign
jsign.name=jsign
jsign.rev=7.3

testng.org=org.testng
testng.name=testng
testng.rev=7.11.0

testng-ant.org=org.testng
testng-ant.name=testng-ant
testng-ant.rev=1.0.0

# General configuration
ivy.report.todir=${basedir}/reports