name: build

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        java: [25]
        arch: [x86_64, aarch64, riscv64]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install makeself firefox chromium nsis
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run:
      - run: ant -Dtarget.arch=${{ matrix.arch }} makeself
      - uses: actions/upload-artifact@v4
        with:
          name: qz-tray-linux-${{ matrix.arch }}
          path: out/qz-tray-*.run
      - if: ${{ matrix.arch == 'x86_64' }}
        run: |
          # Only run tests on same arch
          ant testng
          # Run policy tests again, but as root
          sudo ant -Dtestng.pattern="**/policy/**" testng
          sudo DEBUG=true out/qz-tray-*.run
          /opt/qz-tray/qz-tray --version
          ant nsis

  macos:
    runs-on: [macos-latest]
    strategy:
      matrix:
        java: [25]
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - run: brew install nsis makeself
      - run: brew install --cask google-chrome firefox
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: ant -Dtarget.arch=${{ matrix.arch }} pkgbuild
      - uses: actions/upload-artifact@v4
        with:
          name: qz-tray-macos-${{ matrix.arch }}
          path: out/qz-tray-*.pkg
      - if: ${{ matrix.arch == 'aarch64' }}
        run: |
          # Only run tests on same arch
          ant testng
          # Run policy tests again, but as root
          sudo ant -Dtestng.pattern="**/policy/**" testng
          sudo installer -pkg out/qz-tray-*.pkg -target /
          "/Applications/QZ Tray.app/Contents/MacOS/QZ Tray" --version
          ant makeself
          ant nsis

  windows:
    runs-on: [windows-latest]
    strategy:
      matrix:
        java: [25]
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - run: choco install nsis firefox googlechrome
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: ant "-Dtarget.arch=${{ matrix.arch }}" nsis
      - uses: actions/upload-artifact@v4
        with:
          name: qz-tray-windows-${{ matrix.arch }}
          path: out/qz-tray-*.exe
      - if: ${{ matrix.arch == 'x86_64' }}
        run: |
          # Only run tests on same arch
          ant testng
          Start-Process -Wait ./out/qz-tray-*.exe -ArgumentList "/S"
          "&'C:/Program Files/QZ Tray/qz-tray.exe' --wait --version|Out-Null"


